### PR TITLE
Added libnotify for linux

### PR DESCRIPTION
**Pull request by wavded**
Attached the code for adding libnotify and ran through some tests.  Renamed notifyGrowl to just notify as its using two libs now.

### CODE REVIEW

**Comment by TrevorBurnham** [comment]
Perhaps the growlnotify should used if `process.platform is 'darwin'`, and notify-send should be used otherwise?

**Comment by wavded** [comment]
sure, its been added

**Comment by TrevorBurnham** [comment]
Merged, thanks.

**Comment by MaffooBristol** [comment]
@TrevorBurnham Where has this gone? It doesn't seem to exist any more. Would be very useful as I develop on both Mac and Linux.

Seems it was overwritten by this commit: https://github.com/TrevorBurnham/Jitter/commit/2d05865537b454c2250ec58054497ea96c4f2d99

:cry:

**Pull request merged**
