### PR TITLE
Run tests after changes

### PR DESCRIPTION
**Pull request by dsrw**
I added naive autotest type functionality to jitter, to run my tests after a compile.  It adds an optional 3rd paramater jitter to specify a test directory, and will run everything in the directory after the initial rootCompile, and after any change.  It could be better, but it works for me.

We can only run tests after everything has compiled, so I added a dependency to a small lib I wrote called sink which makes it somewhat easier to impose order on async code.

Thanks for the great utility.

### CODE REVIEW

**Comment by TrevorBurnham** [comment]
Thanks, this is really cool!

I've merged your code in unchanged. The one concern I have is that it seems a bit inelegant to keep the `.coffee` and `.js` files for the tests in the same directory. Also, the approach of compiling and running all of the code in a directory in no particular order is fine for naïve autotesting, but there are other post-compile hooks that people might want, such as concatenating code for production. I'm wondering what the most elegant way of supporting that functionality is, while keeping Jitter simple.

Perhaps the best, approach would be for Jitter to maintain a "lock" file in the CoffeeScript directory that it touches every time compilation succeeds. Then a second utility could monitor that file and act accordingly (running tests or performing concatenation). What do you think?

**Comment by dsrw** [comment]
I definitely like the direction you're headed.  What if, instead of a lock file, we strip down to a super simple "core" that only knows how to monitor and compile, allow for an optional config file that exposes hooks like `compileSucceeded` or `fileChanged`, then provide a few helper functions like `growlNotify` and `concatJS` that people can call from their hooks?

Here's a possible .jitter file:

```
default
  compileFailed: growlNotify
  compileSucceeded: (source, target) ->
    exec "touch jitter.lock" 
    runTests()
    concatJS target
watch 
  source: "src",
  target: "lib"
watch 
  source: "test",
  fileChanged: -> runTests
runTests = -> puts(exec "coffee test/*.coffee")
```

Or something like that.  `exec`, `concatJS` and `growlNotify` are helpers provided with jitter, but anything else could be `require`d in. 

I know this is a bigger change than what you're proposing, and might be overkill, but I think it has some interesting possibilities.  I should be able to come up with a patch in the next few days if you're interested in going this way.  Thoughts?

**Comment by TrevorBurnham** [comment]
That's an awesome idea. I'm trying to reconcile the config-based approach with the command line approach. Here's one possibility:

When `jitter` is run without arguments, it looks for a file called `build.jitter`. If `jitter` is run with one argument, it's assumed to be the name of a config file (with `.jitter` extension optional). If `jitter` is run with two arguments, they're source root and build root. The three-arg command should probably be scrapped, because folks doing anything that sophisticated will save time in the long run by using a `.jitter` file.

Here's my "dream" .jitter file:

```
projectName = "Foo"

watch
  source: "src"
  target: "lib"
  onCompile: (j) ->
    j.concatJS "#{projectName}.js"
    j.minifyJS "#{projectName}.min.js"

watch 
  source: "test"
  onChange: (j) ->
    j.runTests "**/*.coffee"
```

The `j` object would carry state and configuration information so that, for instance, the call to `j.concatJS` wouldn't have to read any files—the JS output would be cached in `j`. Also, the path description passed to `j.runTests` would be relative to the watched path (`"test"` in this case); alternatively, the `source` could be given as `test/**/*.coffee*` and `j.runTests` could be run without arguments.

If you'd like to work on this, then I'll leave it to you for the time being. Thanks!

**Comment by dsrw** [comment]
I like it.

**Comment by TrevorBurnham** [comment]
One additional thought: It'd be great if this super-enhanced Jitter also let you watch and compile, say, Haml and Sass files (and get Growl notifications when those compilations fail). Not sure what the best way to do that is (I'd like a better syntax than putting a bunch of command-line calls in an `onChange` function)... some sort of simple "plugin" function that lets you tell Jitter, "OK, here's what you do when a `.haml` function is in a `source` directory and a `target` directory is specified..."

**Comment by TrevorBurnham** [comment]
Are you writing this new super-Jitter, or should I be working on it? :)

**Comment by dsrw** [comment]
Sorry for the silence.  I got a pretty good start on it last week, but I've been busy with other things since and still have an hour or two of work to tie things together.  I should be able to get an early version into my repo a little later tonight, so you can see where I'm headed.

**Comment by dsrw** [comment]
More silence...

I finally committed my changes to my branch.  There's still work to be done, but it's 90% of the way there.  Hopefully I'll have it ready to merge by tomorrow.

**Pull request merged**
